environment:
  matrix:
    - QTDIR: C:\Qt\5.12\mingw73_32
      MINGW: C:\Qt\Tools\mingw73_32
      COMPILER_NAME: mingw73_32
    - QTDIR: C:\Qt\6.2.0\msvc2019_64
      COMPILER_NAME: msvc2019_64

configuration:
  - release

# Get the project submodules
# Set the environment variables and paths to make
install:
  - git submodule update --init --recursive
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin
  - echo "Printing qtdir..."
  - echo %QTDIR%
  - echo "Moving to and printing out qt dir contents..."
  - cd "%QTDIR%"
  - dir
  - cd "%QTDIR%\bin"
  - dir
  - set myqtenvpath="%QTDIR%\bin\qtenv2.bat"
  - echo "Printing myqtenvpath"
  - echo %myqtenvpath%
  - call "%QTDIR%\bin\qtenv2.bat"
  - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if not %QTDIR:msvc2019=%==%QTDIR% call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
  - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%

  # Get the Qt installer framework
  - cd scripts
  - appveyor_windows_get_ifw.bat
  - cd %APPVEYOR_BUILD_FOLDER%

  # Run qmake
  - qmake CONFIG+=%CONFIGURATION% installer.pro

# Build the project
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - '%make%'
  - ls -a
  - move geometrize_installer.exe geometrize_installer_%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_BUILD_ID%_%COMPILER_NAME%_%CONFIGURATION%.exe
  - echo geometrize_installer_%APPVEYOR_BUILD_NUMBER%_%APPVEYOR_BUILD_ID%_%COMPILER_NAME%_%CONFIGURATION%.exe > __latest

# Gather artifacts
artifacts:
  - path: '**\geometrize_installer*.exe'
    name: geometrize_installer
    type: File
  - path: '**\__latest'
    name: geometrize_latest_tag
    type: File

# Deploy artifacts
deploy:
  provider: S3
  access_key_id: $(AWS_ACCESS_KEY_ID)
  secret_access_key: $(AWS_SECRET_ACCESS_KEY)
  bucket: $(AWS_S3_BUCKET_NAME)
  region: us-east-1
  unzip: false
  set_public: true
  folder: windows/%COMPILER_NAME%