sudo: required
dist: trusty
language: cpp

# Add secure key for Github
env:
  global:
    - secure: dCvCFxn7Kpxw/eOwRpuJAdzj93PzVl2FNCxHrczsizOO56/rWTb3yb53PZJ9avdszuJkY9CVYjP4B7ox6VOW9GS0GJkxExY0+UUb85SnwkWz/60jhHcxmwh+ergBGXrb7pXgi+4h2QoWZa4Wa79EOxfXU5rGesQJRiqV5Sr03dLYQE0Fn3rjQq7hEdFVCmn9Pbn2XR/SA1D37amNzlvjCQzrTRUH9uZyvuJqnkfBTyy9MsUmQXQwe4d7O1+uwFw0XuYNynUwZuLR8IDlNN2/WybS8gjcJQbJuSYXhoAXKKZ0Jk4TS4Y27jBiOsgWR/1nxNGPHG3HPlSmLYDmCBocvgX92oD4QVYpXVgPbYXayJwk9kCXIiYu7HTZnHiHrQzfLjc9SbVk45p6jAh52IamEu1b7bUwG6fuXb/NQHNkc8Ssp4IbieyKhFSoQWLChXQ2KL6wzmMV6vW+hkPqaaAkCBO5fgeL1RWJStudgKhxUEMe9lHB8Jo6ISvUqg+emGc59GzwT82R89C08cpNQ7L7gJVBgzUq4RuPEhPdnrB/kJM2CvhU8V2VYBfppfAdRF5lcESj1fj4VTwwudvPSBBrVP/YEO5OCBI42mw0iJs6Cy1hggA/yLqByTMQDZTkkZCV1Bp5z6OTLCjkdz5HrPNyayo5/Ar3vpGOIC38wCjIwp4=

# Setup build matrix
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  - os: osx
    osx_image: xcode9
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
    - OSX_IMAGE_NAME="xcode_9_0"

before_install:
  # Get the latest version of the Geometrize submodule, and push it to the remote (if necessary)
  - chmod +x ./travis_update_geometrize_submodule.sh
  - ./travis_update_geometrize_submodule.sh

  # Set compilers
  - eval "${MATRIX_EVAL}"
  - echo $CC
  - echo $CXX
  
  # Work around intermittent failures on OSX
  # "Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)"
  # See https://stackoverflow.com/questions/46670305/how-to-change-ruby-version-for-homebrew-in-macos-in-travis-ci/46756693
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi

  # Get Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq --force-yes; fi

install:
  # Install Qt
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt59base qt59svg qt59imageformats qt59tools; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt59/bin/qt59-env.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link qt5 --force; fi

script:
  # Build the installer
  - qmake installer.pro
  - make CC=${CC} CXX=${CXX} LINK=${CXX}

before_deploy:
  - mkdir build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv Geometrize.AppImage build/geometrize_${TRAVIS_JOB_NUMBER}_${TRAVIS_OS_NAME}_${CXX}.AppImage ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv Geometrize.dmg build/geometrize_${TRAVIS_JOB_NUMBER}_${TRAVIS_OS_NAME}_${OSX_IMAGE_NAME}.dmg ; fi
  - popd

# Deploy to Amazon S3
deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: ${AWS_S3_BUCKET_NAME}
  local_dir: build
  skip_cleanup: true
  upload-dir: ${TRAVIS_OS_NAME}
  acl: public_read